main: ssm.simplesafemode.SimpleSafeMode
version: 1.3.5
name: SimpleSafeMode
author: KingXRP, Horwhat
website: www.github.com/DavShaw/


commands:
  simplesafemode:
   description: Just the main command for Simple Safe Mode plugin
  ssm:
    description: Just the main command for Simple Safe Mode plugin